### ISSUE TITLE
Morning session review of week 3

### ISSUE THREAD

**Issue by myelin0** [clintonjosephs/portfolio_website#11]
Compliments on your portfolio looks very nice! 👍 😄 Very well built! Some minor issues to fix are:
-You can take the logo outside of your navigation bar, because some reviewers think that is the way to do it.
-You can include the Hamburger Menu inside the navigation-bar.
-In your mobile view appear Ruby on rails, which should not show there according to Figma`s design.

**Comment by HAMMAS-SALEEM** [comment]
♻️ Great effort! I can see you worked hard and your project looks good 👍 . It could be better if you put your logo outside the nav bar.

**Comment by clintonjosephs** [comment]
Thank you so much for your contribution guys, i have resolved the issues
