### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by mugishasam123** [clintonjosephs/portfolio_website#16]
hey @clintonjosephs  ✋ 

- [ ] while I was trying to look into your codebase I found a bug in the local storage js file on line 9 there undefined variable 
which may cause problems 😟 

- [ ] please kindly define that variable correctly try to add "e" at the end of it to match with your codebase 👍 
- [ ] hope to hear from you after resolving the issue ❤️ 
- [ ] see this link to the bug https://github.com/clintonjosephs/portfolio_website/blob/6757f6eb817f5614b4b51909834a9eb17f4a0f54/assets/js/localstorage.js#L9

**Comment by clintonjosephs** [comment]
Hey Samuel,

Thank you for pointing out that issue, I have resolved it.
